//
//  ACAlertView.h
//  Amity-Care
//
//  Created by Vijay Kumar on 31/03/14.
//  Copyright (c) 2014 OctalInfoSolutions. All rights reserved.
//

#import <UIKit/UIKit.h>

typedef NS_ENUM(NSInteger, ACAlertViewTag) {
    AC_ALERTVIEW_FORGOT_PASSWORD = 0,
    AC_ALERTVIEW_LOGOUT,
    AC_ALERTVIEW_REGISTER_SUCCESSFULLY,
    AC_ALERTVIEW_UPLOAD_IMAGE,
    AC_ALERTVIEW_UPLOAD_VIDEO,
    AC_ALERTVIEW_UPDATE_STATUS,
    AC_ALERTVIEW_STATUS_SUCCESSFULLY,
    AC_ALERTVIEW_PROFIE_UPDATED,
    AC_ALERTVIEW_DOC_UPDATED_SUCCESSFULLY,
    AC_ALERTVIEW_SORT_RECORDS_BY_DATE,
    AC_ALERTVIEW_TASK_ADDED_SUCCESSFULLY,
    AC_ALERTVIEW_TASK_UPDATED_SUCCESSFULLY,
    AC_ALERTVIEW_TASK_DELETED_SUCCESSFULLY,
    AC_ALERTVIEW_OFFLINE_MESSAGE_SUCCESSFULLY,

    AC_ALERTVIEW_CONFIRMATION_TASK_DELETE,
    AC_ALERTVIEW_TASK_STATUS_CHANGED,
    AC_ALERTVIEW_CONFIRM_DELETE_CONTACT,
    AC_ALERTVIEW_DELETE_MSG_CONFIRMATION,
    AC_ALERTVIEW_DELETE_NOTIFICATION_CONFIRMATION,
    AC_ALERTVIEW_DELETE_MAIL_CONFIRMATION,

    AC_ALERTVIEW_ALL_DELETE_NOTIFICATION_CONFIRMATION,
    AC_ALERTVIEW_CHANGE_PASSWORD_ALERT,
    AC_ALERTVIEW_USERS_ASSIGNED_IN_TAG_SUCCESSFULLY,
    AC_ALERTVIEW_CLOCKIN_RECORDS_BY_DATE,
    AC_ALERTVIEW_CLOCKIN_CLOCKOUT,
    AC_ALERTVIEW_OUT_OF_RANGE,
    AC_ALERTVIEW_PIN,
    AC_ALERTVIEW_WRONG_PIN,
};

@interface ACAlertView : UIAlertView
@property(nonatomic,assign) ACAlertViewTag alertTag;
@end
